name: ItemRename
main: org.venompvp.itemrename.ItemRename
author: corin22225
version: 1.0
description: Allows players to rename items with ease.
commands:
  rename:
    description: Renames an item
    permission: itemrename.use
permissions:
  itemrename.use:
    default: false
    description: Lets you use /rename